name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20]  # List of Node.js versions to test with

    steps:
      - name: Checkout RustyRcs repository
        uses: actions/checkout@v3
        with:
          path: RustyRcs

      - name: Checkout rust-rcs-client repository
        uses: actions/checkout@v3
        with:
          repository: Hirohumi/rust-rcs-client
          path: rust-rcs-client

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Set up Android SDK
        run: |
          choco install android-sdk
          $Env:ANDROID_SDK_ROOT = "$Env:ProgramFiles(x86)\Android\android-sdk"
          $Env:PATH += ";$Env:ANDROID_SDK_ROOT\platform-tools"
          $Env:PATH += ";$Env:ANDROID_SDK_ROOT\tools\bin"
          sdkmanager --update
          sdkmanager "platform-tools" "platforms;android-30" "build-tools;30.0.3" "ndk;21.3.6528147"

      - name: Build rust-rcs-client
        run: |
          cd rust-rcs-client
          cargo build --release
        env:
          CARGO_TARGET_DIR: $GITHUB_WORKSPACE/RustyRcs/app/libs

      - name: Build RustyRcs with Gradle
        run: |
          cd $GITHUB_WORKSPACE/RustyRcs
          ./gradlew assembleDebug

      - name: Verify APK exists
        run: |
          ls -l $GITHUB_WORKSPACE/RustyRcs/app/build/outputs/apk/debug/app-debug.apk

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: apk
          path: RustyRcs/app/build/outputs/apk/debug/app-debug.apk
