name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Set up Android SDK
      run: |
        choco install android-sdk --version=4333796
        echo "::add-path::C:\Program Files (x86)\Android\android-sdk\tools\bin"
        echo "::add-path::C:\Program Files (x86)\Android\android-sdk\platform-tools"
        echo "sdkmanager 'platforms;android-30' 'build-tools;30.0.3' 'ndk;21.3.6528147'" | sdkmanager --install

    - name: Install Rust
      run: |
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
        $env:Path += ";$HOME/.cargo/bin"
        rustup target add aarch64-linux-android

    - name: Build Rust libraries
      run: |
        cd rust-part
        cargo build --target aarch64-linux-android

    - name: Build with Gradle
      run: .\gradlew.bat build

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: apk
        path: app/build/outputs/apk/debug/app-debug.apk
