name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20]  # List of Node.js versions to test with

    steps:
      - name: Checkout RustyRcs repository
        uses: actions/checkout@v3
        with:
          path: RustyRcs

      - name: Checkout rust-rcs-client repository
        uses: actions/checkout@v3
        with:
          repository: Hirohumi/rust-rcs-client
          path: rust-rcs-client

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Set up Android SDK
        run: |
          echo "Setting up Android SDK"
          sudo apt-get update
          sudo apt-get install -y openjdk-11-jdk wget unzip
          wget https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip -O sdk-tools.zip
          mkdir -p $HOME/Library/Android/sdk/cmdline-tools
          unzip sdk-tools.zip -d $HOME/Library/Android/sdk/cmdline-tools
          mv $HOME/Library/Android/sdk/cmdline-tools/cmdline-tools $HOME/Library/Android/sdk/cmdline-tools/tools
          export ANDROID_HOME=$HOME/Library/Android/sdk
          export PATH=$PATH:$ANDROID_HOME/emulator:$ANDROID_HOME/tools:$ANDROID_HOME/tools/bin:$ANDROID_HOME/platform-tools
          yes | sdkmanager --licenses
          sdkmanager --update
          sdkmanager "platform-tools" "platforms;android-30" "build-tools;30.0.3" "ndk;21.3.6528147"

      - name: Build rust-rcs-client
        run: |
          cd rust-rcs-client
          cargo build --release
        env:
          CARGO_TARGET_DIR: $GITHUB_WORKSPACE/RustyRcs/app/libs

      - name: Build RustyRcs with Gradle
        run: |
          cd $GITHUB_WORKSPACE/RustyRcs
          ./gradlew assembleDebug

      - name: Verify APK exists
        run: |
          ls -l $GITHUB_WORKSPACE/RustyRcs/app/build/outputs/apk/debug/app-debug.apk

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: apk
          path: RustyRcs/app/build/outputs/apk/debug/app-debug.apk
